type IEnv = {
  NEXT_PUBLIC_NETWORK_ID: string;
  NEXT_PUBLIC_TARGET_CHAIN_ID: string;
  SECRET_COOKIES_PASSWORD: string;
  PINATA_API_KEY: string;
  PINATA_SECRET_API_KEY: string;
  OWNER: string;
  JSON_RPC_URL: string;
};

export const ENV: IEnv = {
  NEXT_PUBLIC_NETWORK_ID: process.env.NEXT_PUBLIC_NETWORK_ID,
  NEXT_PUBLIC_TARGET_CHAIN_ID: process.env.NEXT_PUBLIC_TARGET_CHAIN_ID,
  SECRET_COOKIES_PASSWORD: process.env.SECRET_COOKIES_PASSWORD,
  PINATA_API_KEY: process.env.PINATA_API_KEY,
  PINATA_SECRET_API_KEY: process.env.PINATA_SECRET_API_KEY,
  OWNER: process.env.OWNER,
  JSON_RPC_URL: process.env.JSON_RPC_URL,
};
